### ISSUE TITLE
Uncaught TypeError: this.transferPropsTo is not a function

### ISSUE THREAD

**Issue by jpatel3** [ziad-saab/react-checkbox-group#1]
Running into issue while using it. Complains about this.transferPropsTo is not a function. Any help?

**Comment by jpatel3** [comment]
Its been deprecated. So instead of using transferPropsTo, use the component directly -

render: function() {
    // after building up some object, propsObj that is determined by state
    return this.transferPropsTo(
      Component(propsObj)
    );
  }

Update with following -
render: function() {
    // Assign propsObj here
    return <Component {...propsObj}/>;
}

**Comment by ziad-saab** [comment]
Latest version fixes this issue. Please confirm :)

**Comment by jpatel3** [comment]
Works fine now. Thanks for quick update. 

I would recommend two enhancement -
1. Search within the list
2. Select All

I'll plan to enhance as time permits, thanks for providing the component  :+1:
