### ISSUE TITLE
mapping for dynamic input fields

### ISSUE THREAD

**Issue by bytewiz** [ziad-saab/react-checkbox-group#12]
Hi sorry if this is not a question to raise here,but 

I tried to figure how I could map "Checkbox => ( )" to provide a dynamic amount of checkboxes

but if I try to move it outside "Checkbox => ( )" in a mapping function, I get "checkbox undefined",

Might just be me being blind but are you able to help me on this one?

Thanks in advance and I hope that I have provide enough info

**Comment by ziad-saab** [comment]
Hi @bytewiz definitely a good place to ask questions :) One more thing I need from you: can you show me what you are expecting as an end result? Where do the dynamic boxes data come from?

You can definitely do dynamic checkboxes if you need to :)

**Comment by bytewiz** [comment]
@ziad-saab Thanks for quick reply!

So what I am trying to do is this and it throws an error message saying Checkbox is undefined.

My want result is mapping over a given array (provided a dummy array, I know it doesn't exactly match) and then render X number of checkboxes with value={i.value}.

I hope this makes sense :-) and appreciate your help!

<img width="559" alt="checkboxgroup" src="https://cloud.githubusercontent.com/assets/16811871/14552762/36f0be30-02e1-11e6-90cd-13a03c9cb81d.png">

<img width="589" alt="rendercheckboxes" src="https://cloud.githubusercontent.com/assets/16811871/14552764/37789f80-02e1-11e6-8679-90df36177a68.png">

<img width="1437" alt="error msg" src="https://cloud.githubusercontent.com/assets/16811871/14552763/3749113e-02e1-11e6-8b71-1d4f196788b0.png">

**Comment by ziad-saab** [comment]
Hello @bytewiz it does make sense but I do not see any image. I'll give it a shot:

```javascript
var options = [
  {
    value: "meow",
    name: "Meow"
  },
  {
    value: "purr",
    name: "Purr"
  }
];

function render() {
  return (
    <CheckboxGroup>
      {
        Checkbox => (
          <div>
            {
              options.map(
                option => (
                  <label>
                    <Checkbox value={option.value}/>
                    <span>{option.name}</span>
                  </label>
                )
              )
            }
          </div>
        )
      }
    </CheckboxGroup>
  )
}
```

What do you think?

**Comment by bytewiz** [comment]
@ziad-saab Exactly what I needed! :+1: 

And seems like the images got lost after editting the description, but you got it just right :smiley: 

Thanks! and have a great weekend!

**Comment by ziad-saab** [comment]
@bytewiz I see the images in my email. If you want to use `_renderCheckboxes` all you have to do is pass it the `Checkbox` argument like so:

```javascript
```javascript
Checkbox => (
  <div>
    {_renderCheckboxes(Checkbox)}
  </div>
)
```

Please let me know if it's OK to close the issue now.
```

**Comment by bytewiz** [comment]
@ziad-saab awesome! yes this can be closed :-)

**Comment by softpot9** [comment]
Hi @ziad-saab, I have tested your code in the last version. but not working.

`
var options = [
  {
    value: "meow",
    name: "Meow"
  },
  {
    value: "purr",
    name: "Purr"
  }
];

function render() {
  return (
    <CheckboxGroup>
      {
        Checkbox => (
          <div>
            {
              options.map(
                option => (
                  <label>
                    <Checkbox value={option.value}/>
                    <span>{option.name}</span>
                  </label>
                )
              )
            }
          </div>
        )
      }
    </CheckboxGroup>
  )
}
`

If you possible, please help me for this. I want to mapping for dynamic multiple CheckBoxes.

Thanks
