### ISSUE TITLE
Support 15.0.1

### ISSUE THREAD

**Issue by liquidox** [ziad-saab/react-checkbox-group#13]
I think this one needs updating for 15.0.1?

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' p
rDependencies requirements!
npm ERR! peerinvalid Peer react-checkbox-group@1.0.2 wants react@>= 0.14.0 < 1

**Comment by ziad-saab** [comment]
@liquidox fixing :)

**Comment by ziad-saab** [comment]
@liquidox grab the newest v1.0.3 which ditches peerDependencies

**Comment by liquidox** [comment]
Great thanks!
