### ISSUE TITLE
Update API to match react-radio-group 3.0

### ISSUE THREAD

**Issue by NoNeedToBail** [ziad-saab/react-checkbox-group#17]
React-Radio-Group updated its API in version 3.0 to expose 2 components: a RadioGroup and a Radio, rather than exporting the single component with the function-as-a-child weirdness.

This module should be updated to match.

I'll take a stab at a PR for this.

**Comment by ziad-saab** [comment]
On it, I'd like them to work the same way too. I'll bump the version number to 3.0.0 to match as well.

**Comment by NoNeedToBail** [comment]
I was going to take a stab at doing this myself - would you to like me to leave it to you?

**Comment by ziad-saab** [comment]
Sure thing. I'm using it on many projects so I'll have many live test cases to check before publishing it.

I think I'm almost done, but you know how these things go ;)

**Comment by ziad-saab** [comment]
Fixed with PR #18
