### ISSUE TITLE
wrapper div element has unnecessary (maybe invalid?) attributes

### ISSUE THREAD

**Issue by deepakjois** [ziad-saab/react-checkbox-group#2]
The code below:

```
 <CheckboxGroup ref="mediatype" name="mediatype" value={this.props.fieldValues.mediatype}>
...
</CheckboxGroup>
```
produces a DOM tree like this. 
```
<div name="mediatype" value="video,audio" data-reactid=".0.2.3.2">
...
</div>
```

Including the `name` and `value` attributes is not necessary. Can they be stripped out?

**Comment by ziad-saab** [comment]
@deepakjois thanks for pointing this out. The latest version, `0.1.9`, fixes this.
