### ISSUE TITLE
if checkbox is checked value or not

### ISSUE THREAD

**Issue by kuronaru** [ziad-saab/react-checkbox-group#21]
I'm using this package and i want to customize the design to be like buttons instead of the old fashioned checkbox and label text.

I was able to customize the design but I want to implement onSelected SCSS for the selected value.
I checked the DOM and there's no `checked=true` or `checked` values in the DOM element.

How can i achieve that behavior given this code snippet that I have:

```
<CheckboxGroup className='checkboxes' name='fruits' value={this.state.choices} 
  onChange={e => this.setState({ choices: e })}>
  {
     choiceOptions.map((choice) => {
       return (
         <label key={choice.content}>
             <Checkbox value={choice.content} />{choice.content}
          </label>
        )
     })
  }
</CheckboxGroup>
```

**Comment by ziad-saab** [comment]
Hello @kuronaru ! You should still be able to do `input[type=checkbox]:checked` as normal. Try it out and let me know :)

**Comment by kuronaru** [comment]
Hi @ziad-saab, thanks for replying. 
Can you post a snippet in details? Sorry I'm a bit new on learning web devt, thanks in advance

**Comment by ziad-saab** [comment]
@kuronaru did you get around to trying this? The "Elements" tab of your browser won't show you the updated value of the `checked` property, but the CSS will still work.

**Comment by ziad-saab** [comment]
Closing for now, please re-open if you still need halps :)
