### ISSUE TITLE
Add ability to select "none of the above"

### ISSUE THREAD

**Issue by michaelryancaputo** [ziad-saab/react-checkbox-group#23]
Feature ask: optionally add a field that unselects all of the selected inputs and selects `none`. If the None selection is already made, and another selection is made, None should become unchecked.

**Comment by ziad-saab** [comment]
@michaelryancaputo if you make this checkbox group into a controlled component, you can achieve what you want. another way would be to see the checkbox for the "none of the above" be separate from the checkbox group.

**Comment by evanfreeze** [comment]
@michaelryancaputo If you're setting the checked values based on something saved in state, you can always add a button after your checkboxes that says "Clear All" or something and then use the onChange handler to update the state item you're pulling from to an empty array. That'll trigger a re-render which will uncheck all the boxes.
