### ISSUE TITLE
Version 3.1.1 missing prop-types dependency

### ISSUE THREAD

**Issue by eirikurn** [ziad-saab/react-checkbox-group#26]
My project is not yet using the latest React and 'prop-types', so it broke suddenly after upgrading to the latest "patch" version of react-checkbox-group.

They recommend adding it as a full dependency in libraries:

https://www.npmjs.com/package/prop-types#how-to-depend-on-this-package

**Comment by ziad-saab** [comment]
@eirikurn this is now fixed in v3.3.0 which does not even use prop types :)

**Comment by eirikurn** [comment]
Great! Thanks.
