### ISSUE TITLE
allow limited check

### ISSUE THREAD

**Issue by cyb3rs4pi3n** [ziad-saab/react-checkbox-group#28]
cases for checkbox group to have a limit of 3 selections where after it should not be marked ticked

**Comment by ziad-saab** [comment]
@cyb3rs4pi3n in order to do this you should use the CheckboxGroup as a controlled component. This way, when your onChange callback detects that you are about to add a 4th element, you can simply ignore it.

**Comment by cyb3rs4pi3n** [comment]
Handling is fine, the problem is with the checkbox getting 'marked' even if
its not added to the state group.

**Comment by ziad-saab** [comment]
@cyb3rs4pi3n can you please share an example where this is happening?

**Comment by ziad-saab** [comment]
@cyb3rs4pi3n if this is still an issue please re-open with an example codepen, screencast or similar. Thanks :)
