### ISSUE TITLE
Error: The `Checkbox` component must be used as a child of `CheckboxGroup`.

### ISSUE THREAD

**Issue by michaelryancaputo** [ziad-saab/react-checkbox-group#30]
Hey there, love this component, but the latest change seems to have made it not possible to add labels to checkboxes.

For example, the sample code you provide in your read me no longer works as demonstrated in this: https://www.webpackbin.com/bins/-KsEUWEOrnqzFcQZpbIG

**Comment by ziad-saab** [comment]
@michaelryancaputo thanks! My unit tests weren't even checking for this case. v3.3.1 reverts this change. I'll be adding a test to make sure this doesn't happen again.

**Comment by ziad-saab** [comment]
@michaelryancaputo can you please test `react-checkbox-group@4.0.0-beta` and tell me how it works for you? I fixed the issue you were experiencing and `Checkbox` should now work at every level.

**Comment by clem91** [comment]
Hello, i use react-radio-group so i tried react-checkbox-group but unfortunatly i have the same error 
with the following copied code from the readme:

``` javascript
<CheckboxGroup
          checkboxDepth={2} // This is needed to optimize the checkbox group
          name="fruits"
          value={this.state.fruits}
          onChange={this.handleChange}
        >
          <label><Checkbox value="apple" /> Apple</label>
          <label><Checkbox value="orange" /> Orange</label>
          <label><Checkbox value="watermelon" /> Watermelon</label>
        </CheckboxGroup>
```
Altough the stack trace said that: 

> The above error occurred in the <Checkbox> component:
>     in Checkbox (created by QCM)
>     in label (created by QCM)
>     in div (created by CheckboxGroup)
>     in CheckboxGroup (created by ..........
