### ISSUE TITLE
Error when placing the checkboxes inside an html tag

### ISSUE THREAD

**Issue by marcioaffonso** [ziad-saab/react-checkbox-group#34]
When we try to execute the following code from the readme, we get the following error:
`The Checkbox component must be used as a child of CheckboxGroup.`

Code from the readme:

```
<CheckboxGroup
  name="fruits"
  value={this.state.fruits}
  onChange={this.fruitsChanged}
>
  <label><Checkbox value="apple" />Apple</label>
  <label><Checkbox value="orange" />Orange</label>
  <label><Checkbox value="watermelon" />Watermelon</label>
</CheckboxGroup>
```

**Comment by ziad-saab** [comment]
@marcioaffonso please try the newest version published today, `4.0.0`.

Please note that you need to add a prop `checkboxDepth={2}` to the `<CheckboxGroup>` as you can see in the updated example in README.

Please let me know if it works for you.

**Comment by krazyjakee** [comment]
@marcioaffonso Either set your version to `3.3.2` or `^4.0.0`.

@ziad-saab This works, but can 3.x be patched or rolled back to fix this broken change in the old version?

**Comment by marcioaffonso** [comment]
@ziad-saab it worked! thanks a lot!

**Comment by ziad-saab** [comment]
@krazyjakee I'll look into patching it with a non-breaking change today. But is there anything preventing you from updating to v4?

**Comment by krazyjakee** [comment]
@ziad-saab No problem with 4.0.0, I just feel for anyone who hit this today with a major version locked to 3.

**Comment by ziad-saab** [comment]
Agreed. It was an oversight from my part that caused a breaking change with a minor version. I'm going to find a way to roll it back diligently, without causing more headache.

**Comment by ziad-saab** [comment]
Done. v3.3.4 fixes this without breaking anything :)
