### ISSUE TITLE
What is the prop to disable one checkbox?

### ISSUE THREAD

**Issue by fweffort** [ziad-saab/react-checkbox-group#36]
I need to have the first checkbox always checked and disable.
Can't seem to be able to do that, right?

**Comment by michaelryancaputo** [comment]
Usually it's `checked={true}`.

But this seems like a question better suited for StackOverflow.

**Comment by fweffort** [comment]
to make it checked by default is solved, just need to add to the array, but can't disable one single checkbox from this specific component react-checkbox-group

**Comment by michaelryancaputo** [comment]
Please provide what you have already tried, or an example of the code you are using. Have you tried `disabled={true}`

**Comment by ziad-saab** [comment]
@fweffort can you please show a codepen or similar with your example, and I will tell you how to modify it :)

**Comment by Nasaakaa** [comment]
@fweffort can you show how to solve checked by default?

**Comment by kishorebovi** [comment]
How to keep a checkbox checked by default? The prop **checked={true}** doesn't seem to work.
