### ISSUE TITLE
In the codepen I see a warning: The prop `connectDropTarget` is marked as required in `DragDropContext(DropTarget(SortableContainer))`, but its value is `undefined`.

### ISSUE THREAD

**Issue by tachang** [ziad-saab/react-checkbox-group#37]
console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js:1 Warning: Failed prop type: The prop `connectDropTarget` is marked as required in `DragDropContext(DropTarget(SortableContainer))`, but its value is `undefined`.
    in DragDropContext(DropTarget(SortableContainer)) (at ListInput.js:214)
    in ListInput (created by Demo)
    in Demo

**Comment by michaelryancaputo** [comment]
This looks a lot like a drag and drop issue, not a `react-checkbox-group` issue.

**Comment by tachang** [comment]
Whoops! I totally filed this under the wrong project.

And this library is great! Love it so far.
