### ISSUE TITLE
Compatibility with react 0.14.x

### ISSUE THREAD

**Issue by mzafer** [ziad-saab/react-checkbox-group#4]
I am trying to use this module with a project that uses 0.14.x version of React and getting the below error on installation. Can react-checkbox-group be made to work with 0.14.x version of react.

The package react does not satisfy its siblings' peerDependencies requirements!
Peer react-checkbox-group@0.2.0 wants react@>= 0.13.0 < 1

Thanks

**Comment by ziad-saab** [comment]
@mzafer this should be fixed in 0.3.1
