### ISSUE TITLE
Using Checkbox component in a wrapper

### ISSUE THREAD

**Issue by bipycxp** [ziad-saab/react-checkbox-group#41]
I created component-wrapper for your Checkbox like this:

```javascript
export default class CustomCheckbox extends React.Component {
  ...
  render() {
    ...
    return (
      <div className={...}>
        ...
        <CheckboxInput
              checkboxGroup={checkboxGroup}
              {...checkboxProps}
         />
        ...
      </div>
    )
  }
}
```

and using it in CheckboxGroup with `checkboxDepth` prop:
```javascript
<CheckboxGroup checkboxDepth={2} ...>
  <Checkbox .../>
  <Checkbox .../>
</CheckboxGroup>
```

but it isn't working. Error: `The Checkbox component must be used as a child of CheckboxGroup.`

I think it is because my CustomComponent doesn't have child and your library couldn't find elements with `type === Checkbox` in child tree.

How we can fix it? Could we add optional prop to CheckboxGroup, which will get type of my custom wrapper and check `type === (this.props.customCheckbox || Checkbox)`?
And when library will throw needed props to my custom component I'll throw these props to the wrapped Checkbox.

One of the solutions. I can make pull request. What do you think?

**Comment by durchanek** [comment]
This should be released ASAP because the example is not working now.

**Comment by nettree** [comment]
In my case, when you wrap Checkbox in other elements, you need to specify checkboxDepth, for example, if you have structure like:
let checkboxes = (
<div>
  <label>
     <Checkbox/>
     <Checkbox/>
  </label>
</div>
)

then:

<CheckboxGroup  checkboxDepth={3}>
  {checkboxes}
</CheckboxGroup>

Because checkbox element is in the third level, it works for me, hopefully it works for you as well.

**Comment by lsuarez-tiempo-dev** [comment]
I too am trying to do something similar but with a table
