### ISSUE TITLE
Error: The `Checkbox` component must be used as a child of `CheckboxGroup`.

### ISSUE THREAD

**Issue by m10** [ziad-saab/react-checkbox-group#48]
for  some reason this fails on my setup with `"react": "16.3.2"` and `"react-checkbox-group": "4.0.1"`
```
<CheckboxGroup
        checkboxDepth={2}
        name="fruits"
        value={this.state.fruits}
        onChange={this.fruitsChanged}>

        <label><Checkbox value="apple"/> Apple</label>
        <label><Checkbox value="orange"/> Orange</label>
        <label><Checkbox value="watermelon"/> Watermelon</label>
</CheckboxGroup>
```

i tracked it down to https://github.com/ziad-saab/react-checkbox-group/blob/e233ea0747a6f55ad8b3bb590e6184d6e24b09bb/react-checkbox-group.jsx#L74

it works if i change it to `else if (child.type && child.type.prototype instanceof Checkbox) {`

**Comment by durchanek** [comment]
This should be released ASAP because the example is not working now.

**Comment by wcpaez** [comment]
Home page example is not working.

**Comment by lsuarez-tiempo-dev** [comment]
could the maintainer please  merge  #49 ?

**Comment by thefonso** [comment]
Yo dude? wake up!
