### ISSUE TITLE
Deprecated React.DOM pragma

### ISSUE THREAD

**Issue by a-omsk** [ziad-saab/react-checkbox-group#9]
If i try to use this package with webpack + babel, it throw the error 
> "node_modules/react-checkbox-group/react-checkbox-group.js: The @jsx React.DOM pragma has been deprecated as of React 0.12"

**Comment by ziad-saab** [comment]
@a-omsk that is correct and it should be fixed. However, your babel should skip anything located in `node_modules/` and webpack should be using the straight up .js file by default. If you want assistance with that please show me your webpack config and I'll help. Meanwhile I'm going to take a look at this here :)

**Comment by ziad-saab** [comment]
@a-omsk please update to v0.3.2 to remove the warning :)
